language: node_js
node_js:
  - node
  - "10"
  - "8"

# script: 
#   - npm run test

# deploy:
#   - provider: npm
#     skip_cleanup: true 
#     email: contact@emiliobool.com
#     api_key: $NPM_TOKEN
#     on: 
#       tags: true
