language: node_js
node_js:
  - node

notifications:
  email:
    recipients:
      - contact@emiliobool.com
    on_success: never 
    on_failure: always 
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release